apiVersion: v1
kind: Pod
metadata:
  name : nexus-server
  labels: 
    app: nexus-server
spec:
  containers:
    - name: nexus-server
      image: /grid/nexus
      env:
        - name: CLIENT_REPOSITORY_NAME
          value: "bedrock"
      ports:
        - containerPort: 8081
          protocol: TCP
  imagePullSecrets:
    - name: regsecret
