apiVersion: v1
kind: Service
metadata:
  name: nexus-server
  labels:
    app: nexus-server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: nexus-server
  type: LoadBalancer
